// LeaveManagementSystem(LeaveSync)/angular/src/app/login/login.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  FormsModule,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { RouterModule } from '@angular/router';
import { AuthService } from '../service/auth.service';

@Component({
  selector: 'app-login',
  imports: [CommonModule, ReactiveFormsModule,RouterModule,FormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
})
export class LoginComponent {
  loginForm: FormGroup;
  loginError: string = '';

  constructor(private fb: FormBuilder, private authService:AuthService) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]],
      role:['', [Validators.required]]
    });

  }

  // onSubmit(): void {
  //   if (this.loginForm.valid) {
  //     const { email, password,role } = this.loginForm.value;
  
  //     this.authService.login(email, password,role).subscribe(
  //       (user) => {
  //         if (user) {
  //           console.log('Login Successful:', user);
  //           this.loginError = '';
  //           // You can store the token or user information in localStorage/sessionStorage if needed.
  //           // localStorage.setItem('token', user.token);
  //         } else {
  //           this.loginError = 'Invalid email or password.';
  //         }
  //       },
  //       (error) => {
  //         console.error('Error during login:', error);
  //         this.loginError = 'An error occurred during login. Please try again later.';
  //       }
  //     );
  //   }
  // }
  

  onSubmit(): void {
    if (this.loginForm.valid) {
        const { email, password, role } = this.loginForm.value;

        // Map role to numeric value
        const roleValue = role === 'admin' ? 1 : 2;

        this.authService.login(email, password, roleValue).subscribe(
            (user) => {
                console.log('Login Successful:', user);
                this.loginError = '';
            },
            (error) => {
                console.error('Error during login:', error);
                this.loginError = 'An error occurred during login. Please try again later.';
            }
        );
    }
}
}

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-500 via-indigo-600 to-purple-700">
  <div class="bg-white shadow-lg rounded-lg p-8 w-full max-w-md">
    <h2 class="text-2xl font-bold text-gray-800 mb-6 text-center">
      Login to LeaveMS
    </h2>
    <form (ngSubmit)="onSubmit()" [formGroup]="loginForm" class="space-y-4">
      <!-- Email -->
      <div>
        <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
        <input id="email" type="email" formControlName="email"
          class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
          placeholder="Enter your email" />
        <p *ngIf="
            loginForm.get('email')?.invalid && loginForm.get('email')?.touched
          " class="text-sm text-red-500">
          Please enter a valid email.
        </p>
      </div>
      <!-- Password -->
      <div>
        <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
        <input id="password" type="password" formControlName="password"
          class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
          placeholder="Enter your password" />
        <p *ngIf="
            loginForm.get('password')?.invalid &&
            loginForm.get('password')?.touched
          " class="text-sm text-red-500">
          Password is required.
        </p>
      </div>


      <!-- Role -->
      <div>
        <label for="role" class="block text-sm font-medium text-gray-700">Role</label>
     
        <!-- <select id="role" type="role" formControlName="role" aria-placeholder="Select Role"  
          class="w-full px-4 py-2 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500">
          <option value="" [defaultSelected]="true">Select Role</option>
          <option value="admin">Admin</option>
          <option value="user">User</option>
        </select> -->
      

      <select id="role" formControlName="role" class="w-full px-4 py-2 border border-gray-300 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500">
        <option value="" [defaultSelected]="true">Select Role</option>
        <option value="1">Admin</option>
        <option value="2">User</option>
    </select>
    </div>
    
   

      <!-- Submit Button -->
      <!-- <button [routerLink]="'/dashboard'" type="submit" [disabled]="loginForm.invalid" -->
       <button class="w-full py-2 px-4 bg-indigo-500 hover:bg-indigo-600 text-white font-medium rounded-lg shadow-md focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2">
        Login
      </button>
    </form>
    <p class="mt-4 text-sm text-gray-600 text-center">
      Don’t have an account?
      <a routerLink="/register" class="text-indigo-600 hover:underline">Sign up</a>
    </p>
  </div>
</div>

// leavesync/src/pages/Login.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../lib/supabase";

const Login = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const navigate = useNavigate();

  const handleLogin = async (e) => {
    e.preventDefault();
    setError("");

    try {
      // 1. Login with Supabase
      const { data: loginData, error: loginError } =
        await supabase.auth.signInWithPassword({
          email,
          password,
        });

      if (loginError) throw loginError;

      const user = loginData.user;

      // 2. Check if the user exists in the "Users" table
      const { data, error: userError } = await supabase
        .from("Users")
        .select("*")
        .eq("email", email)
        .single(); // Single ensures we only fetch one record

      if (userError) throw userError;

      if (!data) {
        // No user found, log out
        await supabase.auth.signOut();
        setError("No user found with this email.");
        return;
      }

      // 3. Check if the user is approved
      if (!data.is_accepted) {
        await supabase.auth.signOut();
        setError("This user is blocked by admin.");
        return;
      }

      // 4. Store user in localStorage and redirect
      localStorage.setItem("user", JSON.stringify(data));
      navigate("/dashboard");
    } catch (err) {
      console.error("Login error:", err.message);
      setError(err.message || "Failed to log in.");
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-400 via-purple-500 to-pink-500 p-6">
      <div className="bg-white shadow-2xl rounded-xl p-8 max-w-md w-full">
        <h2 className="text-3xl font-extrabold text-center text-gray-800 mb-6">
          Login to Dashboard 🚀
        </h2>

        {error && <p className="text-red-500 text-center mb-4">{error}</p>}

        <form onSubmit={handleLogin} className="space-y-4">
          <div>
            <label className="block text-gray-700 font-semibold mb-2">
              Email
            </label>
            <input
              type="email"
              placeholder="Enter your email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              className="w-full px-4 py-2 border-2 border-blue-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
            />
          </div>

          <div>
            <label className="block text-gray-700 font-semibold mb-2">
              Password
            </label>
            <input
              type="password"
              placeholder="Enter your password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              className="w-full px-4 py-2 border-2 border-pink-300 rounded-lg focus:ring-2 focus:ring-pink-500 outline-none"
            />
          </div>

          <button
            type="submit"
            className="w-full py-2 px-4 bg-gradient-to-r from-blue-500 to-pink-500 text-white font-bold rounded-lg hover:opacity-90 transition duration-300"
          >
            Login
          </button>
          <div className="text-center mt-6 text-gray-600">
            Dont have an account?{" "}
            <button
              onClick={() => navigate("/sign-up")}
              className="text-blue-500 font-semibold hover:underline transition duration-300"
            >
              Sing up
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Login;
